#!/usr/bin/env python3
"""
Language Manager for GED Document Management System
Supports French and English languages
"""

import streamlit as st
from typing import Dict, Any

class LanguageManager:
    """Manages language translations for the GED system"""
    
    def __init__(self):
        self.translations = {
            "fr": {
                # Navigation
                "navigation": "Navigation",
                "current": "Actuel",
                "quick_links": "Liens rapides",
                "switch_language": "Changer de langue",
                
                # Document Classifier
                "document_classifier": "Classifieur de Documents",
                "upload_documents": "Télécharger des documents",
                "ai_classification": "Classification IA",
                "auto_organization": "Organisation automatique",
                "confidence_scoring": "Score de confiance",
                "upload_files": "Déposez un fichier .pdf, .docx, .jpg, .png :",
                "file_name": "Nom",
                "file_size": "Taille",
                "file_type": "Type",
                "extracted_text": "Texte extrait (cliquez pour voir)",
                "no_text_detected": "Aucun texte détecté dans le document",
                "classification_in_progress": "Classification en cours...",
                "confidence": "Confiance",
                "low_confidence": "confiance faible",
                "file_organization": "Organisation du fichier...",
                "file_classified": "Fichier classé dans",
                "file_classified_low_confidence": "Fichier classé dans avec confiance faible",
                "open_folder": "Ouvrir le dossier",
                "organization_error": "Erreur lors de l'organisation du fichier",
                "detailed_probabilities": "Probabilités détaillées",
                "no_readable_text": "Aucun texte lisible détecté dans le document",
                "empty_document": "Document sans texte classé dans",
                
                # Analytics Dashboard
                "analytics_dashboard": "Tableau de Bord Analytique",
                "monitor_performance": "Surveiller les performances du système",
                "real_time_stats": "Statistiques en temps réel",
                "document_distribution": "Distribution des types de documents",
                "performance_metrics": "Métriques de performance",
                "activity_logs": "Journaux d'activité",
                "total_documents": "Total des Documents",
                "avg_confidence": "Confiance Moyenne",
                "avg_processing_time": "Temps de Traitement Moyen",
                "total_size": "Taille Totale",
                "document_type_distribution": "Distribution des Types de Documents",
                "recent_activity": "Activité Récente",
                "performance_overview": "Aperçu des Performances",
                "processing_time_by_type": "Temps de traitement par type de document",
                "confidence_distribution": "Distribution de la confiance",
                "no_data_available": "Aucune donnée disponible",
                "add_sample_data": "Ajouter des données d'exemple",
                "sample_data_added": "Données d'exemple ajoutées ! Actualisez pour voir les résultats.",
                
                # System
                "ged_system": "Système de Gestion de Documents GED",
                "advanced_platform": "Plateforme Avancée de Classification et d'Analyse de Documents",
                "ml_model": "Modèle ML",
                "analytics": "Analytique",
                "api": "API",
                "active": "Actif",
                "accuracy": "précision",
                "real_time": "Temps réel",
                "port": "Port",
                
                # Options
                "options": "Options",
                "auto_organization": "Organisation automatique",
                "auto_organization_help": "Déplace automatiquement les fichiers vers les dossiers de leur catégorie prédite",
                "warning_threshold": "Seuil d'avertissement",
                "warning_threshold_help": "Affiche un avertissement pour les documents avec confiance < seuil",
                "view_structure": "Voir l'arborescence",
                "folder_structure": "Structure des dossiers :",
                "no_folders_created": "Aucun dossier créé encore",
                "clean_temp": "Nettoyer les dossiers temporaires",
                "cleanup_complete": "Nettoyage effectué",
                
                # Instructions
                "instructions": "Instructions d'utilisation",
                "how_to_use": "Comment utiliser ce classifieur :",
                "step_upload": "📤 Upload : Déposez votre fichier (PDF, DOCX, ou image)",
                "step_analysis": "🔍 Analyse : Le système extrait le texte automatiquement",
                "step_classification": "🤖 Classification : L'IA prédit le type de document",
                "step_organization": "📁 Organisation : Le fichier est automatiquement rangé dans le bon dossier",
                "folder_structure_title": "Structure des dossiers :",
                "main_folder": "documents_classifies/ : Dossier principal",
                "type_folder": "[Type_Document]/ : Un dossier par type de document prédit",
                "empty_folder": "document_vide/ : Documents sans texte détecté",
                "error_folder": "erreur_classification/ : Documents avec erreur de traitement",
                "filename_format": "Format des noms de fichiers :",
                "confidence_format": "[Confiance%]_AAAAMMJJ_HHMMSS_nom_original.ext",
                "low_confidence_format": "[FAIBLE_CONFIANCE_XX%]_... pour les documents avec confiance < 50%",
                "important_note": "📝 Note importante :",
                "classification_note": "Tous les documents sont classés selon la prédiction de l'IA, peu importe le niveau de confiance. Les fichiers avec faible confiance sont simplement marqués dans le nom de fichier.",
                
                # Filters
                "filters": "Filtres",
                "time_period": "Période",
                "days": "jours",
                
                # Status
                "success": "Succès",
                "error": "Erreur",
                "warning": "Avertissement",
                "info": "Information",
                "loading": "Chargement...",
                "processing": "Traitement...",
                "completed": "Terminé",
                "failed": "Échoué",
                
                # Common
                "yes": "Oui",
                "no": "Non",
                "cancel": "Annuler",
                "save": "Sauvegarder",
                "delete": "Supprimer",
                "edit": "Modifier",
                "view": "Voir",
                "refresh": "Actualiser",
                "close": "Fermer",
                "back": "Retour",
                "next": "Suivant",
                "previous": "Précédent",
                "submit": "Soumettre",
                "reset": "Réinitialiser",
                "search": "Rechercher",
                "filter": "Filtrer",
                "sort": "Trier",
                "export": "Exporter",
                "import": "Importer",
                "download": "Télécharger",
                "upload": "Télécharger",
                "settings": "Paramètres",
                "help": "Aide",
                "about": "À propos",
                "contact": "Contact",
                "support": "Support",
                "documentation": "Documentation",
                "version": "Version",
                "update": "Mise à jour",
                "install": "Installer",
                "uninstall": "Désinstaller",
                "configure": "Configurer",
                "test": "Tester",
                "validate": "Valider",
                "verify": "Vérifier",
                "check": "Vérifier",
                "monitor": "Surveiller",
                "log": "Journal",
                "debug": "Déboguer",
                "trace": "Tracer",
                "profile": "Profil",
                "optimize": "Optimiser",
                "analyze": "Analyser",
                "report": "Rapport",
                "dashboard": "Tableau de bord",
                "overview": "Aperçu",
                "summary": "Résumé",
                "details": "Détails",
                "statistics": "Statistiques",
                "metrics": "Métriques",
                "performance": "Performance",
                "efficiency": "Efficacité",
                "quality": "Qualité",
                "accuracy": "Précision",
                "reliability": "Fiabilité",
                "security": "Sécurité",
                "privacy": "Confidentialité",
                "compliance": "Conformité",
                "audit": "Audit",
                "backup": "Sauvegarde",
                "restore": "Restaurer",
                "sync": "Synchroniser",
                "share": "Partager",
                "collaborate": "Collaborer",
                "team": "Équipe",
                "user": "Utilisateur",
                "admin": "Administrateur",
                "guest": "Invité",
                "role": "Rôle",
                "permission": "Permission",
                "access": "Accès",
                "login": "Connexion",
                "logout": "Déconnexion",
                "register": "S'inscrire",
                "password": "Mot de passe",
                "username": "Nom d'utilisateur",
                "email": "Email",
                "phone": "Téléphone",
                "address": "Adresse",
                "company": "Entreprise",
                "department": "Département",
                "position": "Poste",
                "manager": "Manager",
                "employee": "Employé",
                "client": "Client",
                "customer": "Client",
                "vendor": "Fournisseur",
                "partner": "Partenaire",
                "supplier": "Fournisseur",
                "contractor": "Contractant",
                "consultant": "Consultant",
                "advisor": "Conseiller",
                "specialist": "Spécialiste",
                "expert": "Expert",
                "professional": "Professionnel",
                "technician": "Technicien",
                "operator": "Opérateur",
                "analyst": "Analyste",
                "developer": "Développeur",
                "designer": "Designer",
                "architect": "Architecte",
                "engineer": "Ingénieur",
                "scientist": "Scientifique",
                "researcher": "Chercheur",
                "writer": "Rédacteur",
                "editor": "Éditeur",
                "reviewer": "Réviseur",
                "approver": "Approbateur",
                "authorizer": "Autorisateur",
                "supervisor": "Superviseur",
                "coordinator": "Coordinateur",
                "planner": "Planificateur",
                "scheduler": "Planificateur",
                "organizer": "Organisateur",
                "facilitator": "Facilitateur",
                "mediator": "Médiateur",
                "negotiator": "Négociateur",
                "representative": "Représentant",
                "ambassador": "Ambassadeur",
                "delegate": "Délégué",
                "agent": "Agent",
                "broker": "Courtier",
                "trader": "Trader",
                "investor": "Investisseur",
                "stakeholder": "Partie prenante",
                "shareholder": "Actionnaire",
                "owner": "Propriétaire",
                "founder": "Fondateur",
                "co-founder": "Co-fondateur",
                "entrepreneur": "Entrepreneur",
                "businessman": "Homme d'affaires",
                "businesswoman": "Femme d'affaires",
                "executive": "Dirigeant",
                "director": "Directeur",
                "president": "Président",
                "vice_president": "Vice-président",
                "ceo": "PDG",
                "cfo": "CFO",
                "cto": "CTO",
                "coo": "COO",
                "cmo": "CMO",
                "chro": "CHRO",
                "cio": "CIO",
                "cso": "CSO",
                "cpo": "CPO",
                "cdo": "CDO",
                "cgo": "CGO",
                "clo": "CLO"
            },
            "en": {
                # Navigation
                "navigation": "Navigation",
                "current": "Current",
                "quick_links": "Quick Links",
                "switch_language": "Switch Language",
                
                # Document Classifier
                "document_classifier": "Document Classifier",
                "upload_documents": "Upload documents",
                "ai_classification": "AI-powered classification",
                "auto_organization": "Automatic file organization",
                "confidence_scoring": "Confidence scoring",
                "upload_files": "Drop a .pdf, .docx, .jpg, .png file:",
                "file_name": "Name",
                "file_size": "Size",
                "file_type": "Type",
                "extracted_text": "Extracted text (click to see)",
                "no_text_detected": "No text detected in document",
                "classification_in_progress": "Classification in progress...",
                "confidence": "Confidence",
                "low_confidence": "low confidence",
                "file_organization": "File organization...",
                "file_classified": "File classified in",
                "file_classified_low_confidence": "File classified in with low confidence",
                "open_folder": "Open folder",
                "organization_error": "Error during file organization",
                "detailed_probabilities": "Detailed probabilities",
                "no_readable_text": "No readable text detected in document",
                "empty_document": "Document without text classified in",
                
                # Analytics Dashboard
                "analytics_dashboard": "Analytics Dashboard",
                "monitor_performance": "Monitor system performance",
                "real_time_stats": "Real-time statistics",
                "document_distribution": "Document type distribution",
                "performance_metrics": "Performance metrics",
                "activity_logs": "Activity logs",
                "total_documents": "Total Documents",
                "avg_confidence": "Avg Confidence",
                "avg_processing_time": "Avg Processing Time",
                "total_size": "Total Size",
                "document_type_distribution": "Document Type Distribution",
                "recent_activity": "Recent Activity",
                "performance_overview": "Performance Overview",
                "processing_time_by_type": "Processing time by document type",
                "confidence_distribution": "Confidence distribution",
                "no_data_available": "No data available",
                "add_sample_data": "Add Sample Data",
                "sample_data_added": "Sample data added! Refresh to see the results.",
                
                # System
                "ged_system": "GED Document Management System",
                "advanced_platform": "Advanced Document Classification & Analytics Platform",
                "ml_model": "ML Model",
                "analytics": "Analytics",
                "api": "API",
                "active": "Active",
                "accuracy": "accuracy",
                "real_time": "Real-time",
                "port": "Port",
                
                # Options
                "options": "Options",
                "auto_organization": "Automatic organization",
                "auto_organization_help": "Automatically moves files to folders of their predicted category",
                "warning_threshold": "Warning threshold",
                "warning_threshold_help": "Shows a warning for documents with confidence < threshold",
                "view_structure": "View structure",
                "folder_structure": "Folder structure:",
                "no_folders_created": "No folders created yet",
                "clean_temp": "Clean temporary folders",
                "cleanup_complete": "Cleanup completed",
                
                # Instructions
                "instructions": "Usage instructions",
                "how_to_use": "How to use this classifier:",
                "step_upload": "📤 Upload: Drop your file (PDF, DOCX, or image)",
                "step_analysis": "🔍 Analysis: The system extracts text automatically",
                "step_classification": "🤖 Classification: AI predicts document type",
                "step_organization": "📁 Organization: File is automatically organized in the right folder",
                "folder_structure_title": "Folder structure:",
                "main_folder": "documents_classifies/: Main folder",
                "type_folder": "[Document_Type]/: One folder per predicted document type",
                "empty_folder": "document_vide/: Documents without detected text",
                "error_folder": "erreur_classification/: Documents with processing error",
                "filename_format": "Filename format:",
                "confidence_format": "[Confidence%]_YYYYMMDD_HHMMSS_original_name.ext",
                "low_confidence_format": "[LOW_CONFIDENCE_XX%]_... for documents with confidence < 50%",
                "important_note": "📝 Important note:",
                "classification_note": "All documents are classified according to AI prediction, regardless of confidence level. Files with low confidence are simply marked in the filename.",
                
                # Filters
                "filters": "Filters",
                "time_period": "Time Period",
                "days": "days",
                
                # Status
                "success": "Success",
                "error": "Error",
                "warning": "Warning",
                "info": "Information",
                "loading": "Loading...",
                "processing": "Processing...",
                "completed": "Completed",
                "failed": "Failed",
                
                # Common
                "yes": "Yes",
                "no": "No",
                "cancel": "Cancel",
                "save": "Save",
                "delete": "Delete",
                "edit": "Edit",
                "view": "View",
                "refresh": "Refresh",
                "close": "Close",
                "back": "Back",
                "next": "Next",
                "previous": "Previous",
                "submit": "Submit",
                "reset": "Reset",
                "search": "Search",
                "filter": "Filter",
                "sort": "Sort",
                "export": "Export",
                "import": "Import",
                "download": "Download",
                "upload": "Upload",
                "settings": "Settings",
                "help": "Help",
                "about": "About",
                "contact": "Contact",
                "support": "Support",
                "documentation": "Documentation",
                "version": "Version",
                "update": "Update",
                "install": "Install",
                "uninstall": "Uninstall",
                "configure": "Configure",
                "test": "Test",
                "validate": "Validate",
                "verify": "Verify",
                "check": "Check",
                "monitor": "Monitor",
                "log": "Log",
                "debug": "Debug",
                "trace": "Trace",
                "profile": "Profile",
                "optimize": "Optimize",
                "analyze": "Analyze",
                "report": "Report",
                "dashboard": "Dashboard",
                "overview": "Overview",
                "summary": "Summary",
                "details": "Details",
                "statistics": "Statistics",
                "metrics": "Metrics",
                "performance": "Performance",
                "efficiency": "Efficiency",
                "quality": "Quality",
                "accuracy": "Accuracy",
                "reliability": "Reliability",
                "security": "Security",
                "privacy": "Privacy",
                "compliance": "Compliance",
                "audit": "Audit",
                "backup": "Backup",
                "restore": "Restore",
                "sync": "Sync",
                "share": "Share",
                "collaborate": "Collaborate",
                "team": "Team",
                "user": "User",
                "admin": "Admin",
                "guest": "Guest",
                "role": "Role",
                "permission": "Permission",
                "access": "Access",
                "login": "Login",
                "logout": "Logout",
                "register": "Register",
                "password": "Password",
                "username": "Username",
                "email": "Email",
                "phone": "Phone",
                "address": "Address",
                "company": "Company",
                "department": "Department",
                "position": "Position",
                "manager": "Manager",
                "employee": "Employee",
                "client": "Client",
                "customer": "Customer",
                "vendor": "Vendor",
                "partner": "Partner",
                "supplier": "Supplier",
                "contractor": "Contractor",
                "consultant": "Consultant",
                "advisor": "Advisor",
                "specialist": "Specialist",
                "expert": "Expert",
                "professional": "Professional",
                "technician": "Technician",
                "operator": "Operator",
                "analyst": "Analyst",
                "developer": "Developer",
                "designer": "Designer",
                "architect": "Architect",
                "engineer": "Engineer",
                "scientist": "Scientist",
                "researcher": "Researcher",
                "writer": "Writer",
                "editor": "Editor",
                "reviewer": "Reviewer",
                "approver": "Approver",
                "authorizer": "Authorizer",
                "supervisor": "Supervisor",
                "coordinator": "Coordinator",
                "planner": "Planner",
                "scheduler": "Scheduler",
                "organizer": "Organizer",
                "facilitator": "Facilitator",
                "mediator": "Mediator",
                "negotiator": "Negotiator",
                "representative": "Representative",
                "ambassador": "Ambassador",
                "delegate": "Delegate",
                "agent": "Agent",
                "broker": "Broker",
                "trader": "Trader",
                "investor": "Investor",
                "stakeholder": "Stakeholder",
                "shareholder": "Shareholder",
                "owner": "Owner",
                "founder": "Founder",
                "co-founder": "Co-founder",
                "entrepreneur": "Entrepreneur",
                "businessman": "Businessman",
                "businesswoman": "Businesswoman",
                "executive": "Executive",
                "director": "Director",
                "president": "President",
                "vice_president": "Vice President",
                "ceo": "CEO",
                "cfo": "CFO",
                "cto": "CTO",
                "coo": "COO",
                "cmo": "CMO",
                "chro": "CHRO",
                "cio": "CIO",
                "cso": "CSO",
                "cpo": "CPO",
                "cdo": "CDO",
                "cgo": "CGO",
                "clo": "CLO"
            }
        }
        
        # Initialize language from session state or default to French
        if "language" not in st.session_state:
            st.session_state.language = "fr"  # French as default
    
    def get_text(self, key: str) -> str:
        """Get translated text for a given key"""
        # Ensure session state is initialized
        if "language" not in st.session_state:
            st.session_state.language = "fr"  # French as default
        
        lang = st.session_state.language
        return self.translations.get(lang, {}).get(key, key)
    
    def switch_language(self):
        """Switch between French and English"""
        # Ensure session state is initialized
        if "language" not in st.session_state:
            st.session_state.language = "fr"  # French as default
            
        if st.session_state.language == "fr":
            st.session_state.language = "en"
        else:
            st.session_state.language = "fr"
    
    def render_language_selector(self):
        """Render language selector in sidebar"""
        # Ensure session state is initialized
        if "language" not in st.session_state:
            st.session_state.language = "fr"  # French as default
            
        st.sidebar.markdown("---")
        st.sidebar.subheader("🌍 " + self.get_text("switch_language"))
        
        current_lang = "🇫🇷 Français" if st.session_state.language == "fr" else "🇺🇸 English"
        other_lang = "🇺🇸 English" if st.session_state.language == "fr" else "🇫🇷 Français"
        
        if st.sidebar.button(f"🔄 {other_lang}"):
            self.switch_language()
            st.rerun()
        
        st.sidebar.markdown(f"**{current_lang}**")

# Global language manager instance
lang_manager = LanguageManager()
